Repository sid-am-ahd935/Aliahns, pull requests merged in 2022-10, with the labels that each got.

#12 Added Hangman game using Python
  Python/Hangman/Hangman.py
  Python/Hangman/dictionary.txt
  Python/Hangman/list _to_txt.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 Decorated the README.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#22 Conway's game of life
  Python/Conway's game of life/README.md
  Python/Conway's game of life/conway'sGAMEofLIFE.py
Labels: hacktoberfest, hacktoberfest-accepted

#21 Created C++/libmatrix
  C++/libmatrix/README.md
  C++/libmatrix/demo.cpp
  C++/libmatrix/libmatrix.hpp
  C++/libmatrix/library.md
Labels: hacktoberfest, hacktoberfest-accepted

#31 create tic-tac-toe game
  Python/Tic-Tac-Toe/game.py
  Python/Tic-Tac-Toe/requirements.txt
  Python/Tic-Tac-Toe/res/o.png
  Python/Tic-Tac-Toe/res/x.png
Labels: hacktoberfest, hacktoberfest-accepted

#24 Tic-Tac-Toe game using C++
  C++/tic_tac_toe/README.md
  C++/tic_tac_toe/tic_tac_toe.cpp
Labels: hacktoberfest

#33 Added code of snake game
  Snake game/README.md
  Snake game/Snake.py
  Snake game/requirements.txt
Labels: hacktoberfest

#35 Added PasswordGenerator using Python and Tkinter
  Python/PasswordGenerator/README.md
  Python/PasswordGenerator/passwordGenerator.py
Labels: hacktoberfest

#37 Patterns in C++
  C++/Patterns/Diamond.cpp
  C++/Patterns/HollowDiamond.cpp
  C++/Patterns/HollowDiamondSpecial.cpp
  C++/Patterns/ItsDabang.cpp
  C++/Patterns/README.md
  C++/Patterns/char1.cpp
  C++/Patterns/char2.cpp
  C++/Patterns/char3.cpp
  C++/Patterns/char4.cpp
  C++/Patterns/char5.cpp
  C++/Patterns/number1.cpp
  C++/Patterns/number2.cpp
  C++/Patterns/numberCon.cpp
  C++/Patterns/pattern2.cpp
  C++/Patterns/pattern3.cpp
  C++/Patterns/pattern4.cpp
  C++/Patterns/pattern5.cpp
  C++/Patterns/pattern6.cpp
  C++/Patterns/pattern7.cpp
  C++/Patterns/pattern8.cpp
  C++/Patterns/pattern9.cpp
  C++/Patterns/spaceNumber1.cpp
  C++/Patterns/star1.cpp
  C++/Patterns/star2.cpp
  C++/Patterns/starSpace1.cpp
  C++/Patterns/starSpace2.cpp
  C++/Patterns/triangleStar1.cpp
Labels: good first issue, hacktoberfest

#36 DIgital Clock Using Java
  Java/Digital Clock Using Java/Digital Clock.iml
  Java/Digital Clock Using Java/README.md
  Java/Digital Clock Using Java/Screenshot (183).png
  Java/Digital Clock Using Java/Screenshot (184).png
  Java/Digital Clock Using Java/out/production/Digital Clock/com/practice/Main.class
  Java/Digital Clock Using Java/out/production/Digital Clock/com/practice/MyWindow$1.class
  Java/Digital Clock Using Java/out/production/Digital Clock/com/practice/MyWindow.class
  Java/Digital Clock Using Java/src/com/practice/Main.java
  Java/Digital Clock Using Java/src/com/practice/MyWindow.java
Labels: hacktoberfest

#41 New features added to C++/libmatrix
  C++/libmatrix/CHANGELOG.md
  C++/libmatrix/README.md
  C++/libmatrix/demo.cpp
  C++/libmatrix/libmatrix.hpp
  C++/libmatrix/library.md
Labels: enhancement, hacktoberfest

#42 SudokuSolver using java
  Java/Sudoku Solver in java/Readme.md
  Java/Sudoku Solver in java/Screenshot.png
  Java/Sudoku Solver in java/SudokuPuzzle.java
Labels: hacktoberfest

#50 adding mern-crud and age calculator
  Js/AgeCalculator/Readme.md
  Js/AgeCalculator/imgs/one.png
  Js/AgeCalculator/imgs/three.png
  Js/AgeCalculator/imgs/two.png
  Js/AgeCalculator/index.html
  Js/AgeCalculator/script.js
  Js/AgeCalculator/style.css
  Js/MernCrud/Readme.md
  Js/MernCrud/imgs/one.png
  Js/MernCrud/imgs/three.png
  Js/MernCrud/imgs/tow.png
  Js/MernCrud/index.html
  Js/MernCrud/style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#57 Added hospital management system
  C++/hms/hosp.cpp
Labels: hacktoberfest

#59 Pascal.
  Java/PascalTriangle/Capture.JPG
  Java/PascalTriangle/Readme.md
  Java/PascalTriangle/pattern.java
Labels: good first issue, hacktoberfest

#48 Updated python folder by adding pyramid pattern
  Python/Pyramid_pattern/README.md
  Python/Pyramid_pattern/pyramid_pattern.py
Labels: hacktoberfest, hacktoberfest-accepted

#63 Adding Password Generator in Java
  Java/Random Password Generator Java/README.md
  Java/Random Password Generator Java/Screenshot 2022-10-19 232907.jpg
  Java/Random Password Generator Java/src/App.java
Labels: good first issue, hacktoberfest

#64 Temperature Converter Web-App
  JavaScript/TempConverter/README.md
  JavaScript/TempConverter/imgs/ExampleOne.png
  JavaScript/TempConverter/imgs/ExapmleDefault.png
  JavaScript/TempConverter/imgs/ExapmleThree.png
  JavaScript/TempConverter/imgs/ExapmleTwo.png
  JavaScript/TempConverter/imgs/arrow.svg
  JavaScript/TempConverter/imgs/bg.jfif
  JavaScript/TempConverter/index.html
  JavaScript/TempConverter/script.js
  JavaScript/TempConverter/style.css
Labels: good first issue, hacktoberfest

#73 A new project named Amazon web scraping is added in the Amazon web scraping folder and in the amazon.py file.
  Java/Sec min & min array/readme.md
  Java/Sec min & min array/sec_min.java
Labels: good first issue, hacktoberfest

#75 created multiple swapping methods in Java
  Java/Multiple Swapping Methods/README.md
  Java/Multiple Swapping Methods/Screenshot_20221024_083521.png
  Java/Multiple Swapping Methods/swap.java
Labels: good first issue, hacktoberfest

#76 Updated and Formatted Swap.java
  Java/Multiple Swapping Methods/swap.java
Labels: enhancement, good first issue, hacktoberfest

#81 Created Simple Calculator in Java
  Java/Simple Calculator/Calculator.java
  Java/Simple Calculator/Screenshot_20221025_094017.png
Labels: good first issue, hacktoberfest

#83 Created Pascal Triangle Pattern in C++
  C++/Pascal Triangle Pattern/Pascal Triangle Pattern.cpp
  C++/Pascal Triangle Pattern/Screenshot_20221026_013630.png
  C++/Pascal Triangle Pattern/temp.exe
Labels: good first issue, hacktoberfest

#85 WeatherBuddy - ReactJS
  JavaScript/TempConverter/imgs/ExampleDefault.png
  JavaScript/TempConverter/imgs/ExampleThree.png
  JavaScript/TempConverter/imgs/ExampleTwo.png
  JavaScript/TempConverter/index.html
  ReactJS/README.md
  ReactJS/WeatherBuddy/.gitignore
  ReactJS/WeatherBuddy/README.md
  ReactJS/WeatherBuddy/img/five.png
  ReactJS/WeatherBuddy/img/four.png
  ReactJS/WeatherBuddy/img/one.png
  ReactJS/WeatherBuddy/img/three.png
  ReactJS/WeatherBuddy/img/two.png
  ReactJS/WeatherBuddy/package-lock.json
  ReactJS/WeatherBuddy/package.json
  ReactJS/WeatherBuddy/public/img/logo.jpg
  ReactJS/WeatherBuddy/public/index.html
  ReactJS/WeatherBuddy/public/manifest.json
  ReactJS/WeatherBuddy/src/App.js
  ReactJS/WeatherBuddy/src/MainCard/MainCard.jsx
  ReactJS/WeatherBuddy/src/app.css
  ReactJS/WeatherBuddy/src/index.js
Labels: hacktoberfest

#53 Some Basic Program in C++
  C++/Important Miscellaneous Programs/AnagramCheck.cpp
  C++/Important Miscellaneous Programs/BreakAPalindrome.cpp
  C++/Important Miscellaneous Programs/BucketSort.cpp
  C++/Important Miscellaneous Programs/CountingSort.cpp
  C++/Important Miscellaneous Programs/DNF_sort.cpp
  C++/Important Miscellaneous Programs/DayToDate.cpp
  C++/Important Miscellaneous Programs/Heap Sort Max Heapify.cpp
  C++/Important Miscellaneous Programs/JosephusProblem.cpp
  C++/Important Miscellaneous Programs/KMP_algorithm.cpp
  C++/Important Miscellaneous Programs/Kadane's_alg.cpp
  C++/Important Miscellaneous Programs/LastOccurence.cpp
  C++/Important Miscellaneous Programs/LinearSearch.cpp
  C++/Important Miscellaneous Programs/LinearSearch_recursion.cpp
  C++/Important Miscellaneous Programs/Longest_Common_Subsequence.cpp
  C++/Important Miscellaneous Programs/MatrixRotation.cpp
  C++/Important Miscellaneous Programs/MatrixTranspose.cpp
  C++/Important Miscellaneous Programs/Minimum_Falling_Path_Sum.cpp
  C++/Important Miscellaneous Programs/Minimum_Square_Problem.cpp
  C++/Important Miscellaneous Programs/NumberIntoEnglishWordClass.cpp
  C++/Important Miscellaneous Programs/Reverse_integer.cpp
  C++/Important Miscellaneous Programs/SelectionSort.cpp
  C++/Important Miscellaneous Programs/SkylineProblem.cpp
  C++/Important Miscellaneous Programs/Snake_Ladder_Problem.cpp
  C++/Important Miscellaneous Programs/SpiralTraversal.cpp
  C++/Important Miscellaneous Programs/Stack.cpp
  C++/Important Miscellaneous Programs/TopoSort.cpp
  C++/Important Miscellaneous Programs/TowerOfHanoi.cpp
  C++/Important Miscellaneous Programs/WaterFlow.cpp
  C++/Important Miscellaneous Programs/WaveSort.cpp
  C++/Important Miscellaneous Programs/binarySearch.cpp
  C++/Important Miscellaneous Programs/binarySearchRecursive.cpp
  C++/Important Miscellaneous Programs/bubblesort.cpp
  C++/Important Miscellaneous Programs/coin_change_problem.cpp
  C++/Important Miscellaneous Programs/countGoodNodesInTree.cpp
  C++/Important Miscellaneous Programs/decimaltobinry.cpp
  C++/Important Miscellaneous Programs/edit_distance.cpp
  C++/Important Miscellaneous Programs/factorial_recursion.cpp
  C++/Important Miscellaneous Programs/heapSort.cpp
  C++/Important Miscellaneous Programs/insertionsort.cpp
  C++/Important Miscellaneous Programs/isPrime.cpp
  C++/Important Miscellaneous Programs/iterativeReverseLinklist.cpp
  C++/Important Miscellaneous Programs/kclosetElements.cpp
  C++/Important Miscellaneous Programs/knapsack_problem.cpp
  C++/Important Miscellaneous Programs/kthElementInTheArray.cpp
  C++/Important Miscellaneous Programs/levelOrder_binaryTree_traversal.cpp
  C++/Important Miscellaneous Programs/linkedlist_creation.cpp
  C++/Important Miscellaneous Programs/mergesort.cpp
  C++/Important Miscellaneous Programs/palindrome-linked-list.cpp
  C++/Important Miscellaneous Programs/queneUsingStack.cpp
  C++/Important Miscellaneous Programs/quickSort.cpp
  C++/Important Miscellaneous Programs/recursiveReverseLinklist.cpp
  C++/Important Miscellaneous Programs/searchbst.cpp
  C++/Important Miscellaneous Programs/selection sort.cpp
  C++/Important Miscellaneous Programs/sort012.cpp
  C++/Important Miscellaneous Programs/stackUsingQuene.cpp
  C++/Important Miscellaneous Programs/trappingRainWater.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#86 Weather report by any city (Amir Sohail Mallick)
  JavaScript/Weather_Status_Any_City/img/Screenshot 1.png
  JavaScript/Weather_Status_Any_City/img/Screenshot 2.png
  JavaScript/Weather_Status_Any_City/img/Screenshot 3.png
  JavaScript/Weather_Status_Any_City/img/Screenshot 4.png
  JavaScript/Weather_Status_Any_City/img/Screenshot 5.png
  JavaScript/Weather_Status_Any_City/img/bg.jpg
  JavaScript/Weather_Status_Any_City/index.html
  JavaScript/Weather_Status_Any_City/script.js
  JavaScript/Weather_Status_Any_City/style.css
Labels: hacktoberfest

#93 Created Bubble Sort Using Cython
  Cython/.gitignore
  Cython/Bubble Sort/cython_sorting/__init__.py
  Cython/Bubble Sort/cython_sorting/cython_bubble_sort.pyx
  Cython/Bubble Sort/main.py
  Cython/Bubble Sort/python_sorting/__init__.py
  Cython/Bubble Sort/python_sorting/python_bubble_sort.py
  Cython/README.md
Labels: good first issue, hacktoberfest

#94 issue solve of dice game
  JavaScript/Dicegame/Readme.md
  JavaScript/Dicegame/dicee.html
  JavaScript/Dicegame/images/dice1.png
  JavaScript/Dicegame/images/dice2.png
  JavaScript/Dicegame/images/dice3.png
  JavaScript/Dicegame/images/dice4.png
  JavaScript/Dicegame/images/dice5.png
  JavaScript/Dicegame/images/dice6.png
  JavaScript/Dicegame/images/one.png
  JavaScript/Dicegame/images/three.png
  JavaScript/Dicegame/images/two.png
  JavaScript/Dicegame/index.js
  JavaScript/Dicegame/styles.css
Labels: hacktoberfest
